feat: Qas052 update gitactions workflows to use secrets (#2089)
* Removed .env test files, updated Playwright .gitignore, updated Playwright UK Login Test workflow

* Playwright.config.ts updated

* playwright.config.ts updated

* Update playwright uk workflow

* Updated Playwright login workflow

* Updated playwright uk workflow

* Updated Playwright login workflows to use secrets

* Updated login test workflows

* Updated Playwright aus workflow

* Updated playwright login workflows - re-added slack notification action

diff --git a/.github/workflows/playwright-aus-login-test.yml b/.github/workflows/playwright-aus-login-test.yml
--- a/.github/workflows/playwright-aus-login-test.yml
+++ b/.github/workflows/playwright-aus-login-test.yml
@@ -8,6 +8,7 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
+    environment: Production
     steps:
       # Checkout repo and install dependencies
       - name: Checkout repository
@@ -25,10 +26,44 @@ jobs:
         working-directory: packages/web-playwright-tests
         run: npx playwright install
 
-      # Run specified Playwright test with retry logic
+      # Check if secrets exist and throw error if any are missing
+      - name: Check Secrets Existence
+        env:
+          BASE_URL_AUS: ${{ secrets.BASE_URL_AUS }}
+          EMAIL_AUS: ${{ secrets.EMAIL_AUS }}
+          PASSWORD_AUS: ${{ secrets.PASSWORD_AUS }}
+        run: |
+          echo "Checking secrets existence..."
+
+          if [ -z "$BASE_URL_AUS" ]; then
+            echo "Error: BASE_URL_AUS secret is not set."
+            exit 1
+          else
+            echo "BASE_URL_AUS secret is set."
+          fi
+
+          if [ -z "$EMAIL_AUS" ]; then
+            echo "Error: EMAIL_AUS secret is not set."
+            exit 1
+          else
+            echo "EMAIL_AUS secret is set."
+          fi
+
+          if [ -z "$PASSWORD_AUS" ]; then
+            echo "Error: PASSWORD_AUS secret is not set."
+            exit 1
+          else
+            echo "PASSWORD_AUS secret is set."
+          fi
+
+      # Run specified Playwright test with retry logic, using secrets for credentials
       - name: Run Playwright test - Login to AUS
         working-directory: packages/web-playwright-tests
         id: playwright
+        env:
+          BASE_URL_AUS: ${{ secrets.BASE_URL_AUS }}
+          EMAIL_AUS: ${{ secrets.EMAIL_AUS }}
+          PASSWORD_AUS: ${{ secrets.PASSWORD_AUS }}
         run: |
           for i in {1..2}; do
             if npx playwright test -g "@Aus @SmokeTest @Web @NeedsTestCase - Login to aus home page"; then
@@ -57,6 +92,6 @@ jobs:
         run: |
           WORKFLOW_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
           curl -X POST -H 'Content-type: application/json' --data '{
-            "text": "*Playwright Web test `Login to aus home page` has failed after 3 attempts against production - Login may not be functioning correctly. Check the workflow run report ('"$WORKFLOW_URL"') for further details.*",
+            "text": "*Playwright Web test `Login to AUS home page` has failed after 3 attempts against production - Login may not be functioning correctly. Check the workflow run report ('"$WORKFLOW_URL"') for further details.*",
             "mrkdwn": true
           }' ${{ vars.CI_NOTIFICATIONS_WEBHOOK }}
diff --git a/.github/workflows/playwright-dds-login-test.yml b/.github/workflows/playwright-dds-login-test.yml
--- a/.github/workflows/playwright-dds-login-test.yml
+++ b/.github/workflows/playwright-dds-login-test.yml
@@ -8,6 +8,7 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
+    environment: Production
     steps:
       # Checkout repo and install dependencies
       - name: Checkout repository
@@ -25,10 +26,44 @@ jobs:
         working-directory: packages/web-playwright-tests
         run: npx playwright install
 
-      # Run specified Playwright test with retry logic
+      # Check if secrets exist and throw error if any are missing
+      - name: Check Secrets Existence
+        env:
+          BASE_URL_DDS: ${{ secrets.BASE_URL_DDS }}
+          EMAIL_DDS: ${{ secrets.EMAIL_DDS }}
+          PASSWORD_DDS: ${{ secrets.PASSWORD_DDS }}
+        run: |
+          echo "Checking secrets existence..."
+
+          if [ -z "$BASE_URL_DDS" ]; then
+            echo "Error: BASE_URL_DDS secret is not set."
+            exit 1
+          else
+            echo "BASE_URL_DDS secret is set."
+          fi
+
+          if [ -z "$EMAIL_DDS" ]; then
+            echo "Error: EMAIL_DDS secret is not set."
+            exit 1
+          else
+            echo "EMAIL_DDS secret is set."
+          fi
+
+          if [ -z "$PASSWORD_DDS" ]; then
+            echo "Error: PASSWORD_DDS secret is not set."
+            exit 1
+          else
+            echo "PASSWORD_DDS secret is set."
+          fi
+
+      # Run specified Playwright test with retry logic, using secrets for credentials
       - name: Run Playwright test - Login to DDS
         working-directory: packages/web-playwright-tests
         id: playwright
+        env:
+          BASE_URL_DDS: ${{ secrets.BASE_URL_DDS }}
+          EMAIL_DDS: ${{ secrets.EMAIL_DDS }}
+          PASSWORD_DDS: ${{ secrets.PASSWORD_DDS }}
         run: |
           for i in {1..2}; do
             if npx playwright test -g "@Dds @SmokeTest @Web @NeedsTestCase - Login to dds home page"; then
diff --git a/.github/workflows/playwright-uk-login-test.yml b/.github/workflows/playwright-uk-login-test.yml
--- a/.github/workflows/playwright-uk-login-test.yml
+++ b/.github/workflows/playwright-uk-login-test.yml
@@ -8,6 +8,7 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
+    environment: Production
     steps:
       # Checkout repo and install dependencies
       - name: Checkout repository
@@ -25,10 +26,44 @@ jobs:
         working-directory: packages/web-playwright-tests
         run: npx playwright install
 
-      # Run specified Playwright test with retry logic
+      # Check if secrets exist and throw error if any are missing
+      - name: Check Secrets Existence
+        env:
+          BASE_URL_UK: ${{ secrets.BASE_URL_UK }}
+          EMAIL_UK: ${{ secrets.EMAIL_UK }}
+          PASSWORD_UK: ${{ secrets.PASSWORD_UK }}
+        run: |
+          echo "Checking secrets existence..."
+
+          if [ -z "$BASE_URL_UK" ]; then
+            echo "Error: BASE_URL_UK secret is not set."
+            exit 1
+          else
+            echo "BASE_URL_UK secret is set."
+          fi
+
+          if [ -z "$EMAIL_UK" ]; then
+            echo "Error: EMAIL_UK secret is not set."
+            exit 1
+          else
+            echo "EMAIL_UK secret is set."
+          fi
+
+          if [ -z "$PASSWORD_UK" ]; then
+            echo "Error: PASSWORD_UK secret is not set."
+            exit 1
+          else
+            echo "PASSWORD_UK secret is set."
+          fi
+
+      # Run specified Playwright test with retry logic, using secrets for credentials
       - name: Run Playwright test - Login to UK
         working-directory: packages/web-playwright-tests
         id: playwright
+        env:
+          BASE_URL_UK: ${{ secrets.BASE_URL_UK }}
+          EMAIL_UK: ${{ secrets.EMAIL_UK }}
+          PASSWORD_UK: ${{ secrets.PASSWORD_UK }}
         run: |
           for i in {1..2}; do
             if npx playwright test -g "@Uk @SmokeTest @Web @NeedsTestCase - Login to uk home page"; then
@@ -51,7 +86,7 @@ jobs:
           name: playwright-report
           path: packages/web-playwright-tests/html-report
 
-      # Send Slack message if all retries fail
+        # Send Slack message if all retries fail
       - name: Send Slack message on fail
         if: failure()
         run: |
